version: "3.8"
services:
  rabbitmq-tp2:
    container_name: "rabbitmq-tp2"
    image: rabbitmq:3.9.7-management-alpine
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - ej3-network
  
  drop-input-column-questions1:
    container_name: drop-input-column-questions1
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop
      - OPERATOR_PARAMS={"columns_to_keep":["OwnerUserId","Score"],"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":1}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-questions"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"exchange-drop-questions"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - ej3-network
  
  drop-input-column-answers1:
    container_name: drop-input-column-answers1
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop
      - OPERATOR_PARAMS={"columns_to_keep":["OwnerUserId","Score"],"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":1}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-answers"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"exchange-drop-answers"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - ej3-network
  
  user_avg_holder_questions:
    container_name: user_avg_holder_questions
    image: building-block:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=holders.user_avg_holder
      - OPERATOR_PARAMS={"perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"exchange-drop-questions","routing_key":"0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"user_avg_holder_questions-output"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=0
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_holder.py"]
    networks:
      - ej3-network
  
  user_avg_holder_answers:
    container_name: user_avg_holder_answers
    image: building-block:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=holders.user_avg_holder
      - OPERATOR_PARAMS={"perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"exchange-drop-answers","routing_key":"0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"user_avg_holder_answers-output"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=0
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_holder.py"]
    networks:
      - ej3-network

networks:
  ej3-network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.203.0/24