version: "3.8"
services:
  rabbitmq-tp2:
    container_name: "rabbitmq-tp2"
    image: rabbitmq:3.9.7-management-alpine
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - ej3-network

  input_node_questions:
    container_name: input_node_questions
    image: input_node:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - FILE_TO_PROCESS=data/red_questions.csv
      - CHUNK_SIZE=1000
      - OUTPUT_QUEUE_NAME=input-questions
      - CENTINELS_TO_SEND=2
    depends_on:
      - "rabbitmq-tp2"
    volumes:
      - "./data:/app/data"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "input_node.py"]
    networks:
      - ej3-network
  
  input_node_answers:
    container_name: input_node_answers
    image: input_node:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - FILE_TO_PROCESS=data/red_answers.csv
      - CHUNK_SIZE=100
      - OUTPUT_QUEUE_NAME=input-answers
      - CENTINELS_TO_SEND=2
    depends_on:
      - "rabbitmq-tp2"
    volumes:
      - "./data:/app/data"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "input_node.py"]
    networks:
      - ej3-network
 
  drop-input-column-questions1:
    container_name: drop-input-column-questions1
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop
      - OPERATOR_PARAMS={"columns_to_keep":["OwnerUserId","Score"],"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":2}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-questions"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"exchange-drop-questions"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=3
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - ej3-network

  drop-input-column-questions2:
    container_name: drop-input-column-questions2
    image: building-block:latest
    environment: 
      - BLOCK_ID=2
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop
      - OPERATOR_PARAMS={"columns_to_keep":["OwnerUserId","Score"],"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":2}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-questions"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"exchange-drop-questions"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=3
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - ej3-network
  
  drop-input-column-answers1:
    container_name: drop-input-column-answers1
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop
      - OPERATOR_PARAMS={"columns_to_keep":["OwnerUserId","Score"],"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":2}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-answers"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"exchange-drop-answers"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=3
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - ej3-network
  
  drop-input-column-answers2:
    container_name: drop-input-column-answers2
    image: building-block:latest
    environment: 
      - BLOCK_ID=2
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop
      - OPERATOR_PARAMS={"columns_to_keep":["OwnerUserId","Score"],"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":2}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-answers"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"exchange-drop-answers"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=3
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - ej3-network
  
  user_avg_holder_questions1:
    container_name: user_avg_holder_questions1
    image: building-block:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=holders.user_avg_holder
      - OPERATOR_PARAMS={"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":1}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"exchange-drop-questions","routing_key":"0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"user-questions-filter-input"}
      - CENTINELS_TO_RECEIVE=2
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_holder.py"]
    networks:
      - ej3-network

  user_avg_holder_questions2:
    container_name: user_avg_holder_questions2
    image: building-block:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=holders.user_avg_holder
      - OPERATOR_PARAMS={"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":1}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"exchange-drop-questions","routing_key":"1"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"user-questions-filter-input"}
      - CENTINELS_TO_RECEIVE=2
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_holder.py"]
    networks:
      - ej3-network
  
  user_avg_holder_answers1:
    container_name: user_avg_holder_answers1
    image: building-block:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=holders.user_avg_holder
      - OPERATOR_PARAMS={"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":1}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"exchange-drop-answers","routing_key":"0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"user-answers-filter-input"}
      - CENTINELS_TO_RECEIVE=2
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_holder.py"]
    networks:
      - ej3-network

  user_avg_holder_answers2:
    container_name: user_avg_holder_answers2
    image: building-block:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=2
      - OPERATOR_MODULE=holders.user_avg_holder
      - OPERATOR_PARAMS={"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":1}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"exchange-drop-answers","routing_key":"1"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"user-answers-filter-input"}
      - CENTINELS_TO_RECEIVE=2
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_holder.py"]
    networks:
      - ej3-network
  
  general_avg_answers:
    container_name: general_avg_answers
    image: building-block:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=holders.general_avg
      - OPERATOR_PARAMS={"perform_affinity":true,"affinity_divider":1}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"exchange-drop-answers","routing_key":"*"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"user-answers-filter-input"}
      - CENTINELS_TO_RECEIVE=6
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_holder.py"]
    networks:
      - ej3-network
  
  general_avg_questions:
    container_name: general_avg_questions
    image: building-block:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=holders.general_avg
      - OPERATOR_PARAMS={"perform_affinity":true,"affinity_divider":1}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"exchange-drop-questions","routing_key":"*"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"user-questions-filter-input"}
      - CENTINELS_TO_RECEIVE=6
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_holder.py"]
    networks:
      - ej3-network

  user-answers-filter:
    container_name: user-answers-filter
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.user_avg_filter
      - OPERATOR_PARAMS={"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":1}
      - INPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"user-answers-filter-input","routing_key":"0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"intersector-input"}
      - CENTINELS_TO_RECEIVE=3
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - ej3-network
  
  user-questions-filter:
    container_name: user-questions-filter
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.user_avg_filter
      - OPERATOR_PARAMS={"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":1}
      - INPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"user-questions-filter-input","routing_key":"0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"intersector-input"}
      - CENTINELS_TO_RECEIVE=3
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - ej3-network
  
  user-intersector:
    container_name: user-intersector
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.intersector
      - OPERATOR_PARAMS={"perform_affinity":false,"affinity_key":"OwnerUserId","affinity_divider":1}
      - INPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"intersector-input","routing_key":"0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"top-n-users-input"}
      - CENTINELS_TO_RECEIVE=2
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - ej3-network
  
  top-n-users:
    container_name: top-n-users
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=holders.top_n_users_holder
      - OPERATOR_PARAMS={"top_n":10}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"top-n-users-input"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"final_output"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=0
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_holder.py"]
    networks:
      - ej3-network

networks:
  ej3-network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.203.0/24