version: "3.8"
services:
  rabbitmq-tp2:
    container_name: "rabbitmq-tp2"
    image: rabbitmq:3.9.7-management-alpine
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - tp2-network
  
  # input_node:
  #   container_name: input_node
  #   image: input_node:latest
  #   environment: 
  #     - PYTHONUNBUFFERED=1
  #     - FILE_TO_PROCESS=data/red_answers.csv
  #     - CHUNK_SIZE=3
  #     - OUTPUT_QUEUE_NAME=input-queue
  #     - NEXT_STEP_COUNT=1
  #   depends_on:
  #     - "rabbitmq-tp2"
  #   volumes:
  #     - "./data:/app/data"
  #   command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "input_node.py"]
  #   networks:
  #     - tp2-network
  
  drop-input-column:
    container_name: drop-input-column
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop
      - OPERATOR_PARAMS={"columns_to_keep":["Score","Body"], "perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-output"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"drop-output"}
      - PREVIOUS_STEP_COUNT=1
      - NEXT_STEP_COUNT=2
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - tp2-network

  filter-column1:
    container_name: filter-column1
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.filter
      - OPERATOR_PARAMS={"keep_columns":["Body"],"column":"Score","to_compare":10,"op":">", "perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"drop-output"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"filter-output"}
      - PREVIOUS_STEP_COUNT=1
      - NEXT_STEP_COUNT=2
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - tp2-network

  filter-column2:
    container_name: filter-column2
    image: building-block:latest
    environment: 
      - BLOCK_ID=2
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.filter
      - OPERATOR_PARAMS={"keep_columns":["Body"],"column":"Score","to_compare":10,"op":">", "perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"drop-output"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"filter-output"}
      - PREVIOUS_STEP_COUNT=1
      - NEXT_STEP_COUNT=2
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - tp2-network
  
  sentiment-analyser1:
    container_name: sentiment-analyser1
    image: building-block:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=operators.sentiment_analysis
      - OPERATOR_PARAMS={"column":"Body", "perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"filter-output"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"sa-output"}
      - PREVIOUS_STEP_COUNT=2
      - NEXT_STEP_COUNT=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - tp2-network

  sentiment-analyser2:
    container_name: sentiment-analyser2
    image: building-block:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=2
      - OPERATOR_MODULE=operators.sentiment_analysis
      - OPERATOR_PARAMS={"column":"Body", "perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"filter-output"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"sa-output"}
      - PREVIOUS_STEP_COUNT=2
      - NEXT_STEP_COUNT=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - tp2-network
  
  avg-holder:
    container_name: avg-holder
    image: building-block:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=holders.avg_holder
      - OPERATOR_PARAMS={"column":"result", "perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"sa-output"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"final-output"}
      - PREVIOUS_STEP_COUNT=2
      - NEXT_STEP_COUNT=0
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_holder.py"]
    networks:
      - tp2-network

networks:
  tp2-network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.201.0/24
