version: "3.8"
services:
  rabbitmq-tp2:
    container_name: "rabbitmq-tp2"
    image: rabbitmq:3.9.7-management-alpine
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - ej2-network

  drop-input-column-answers:
    container_name: drop-input-column-answers
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop
      - OPERATOR_PARAMS={"columns_to_keep":["ParentId","CreationDate", "Score"],"perform_affinity":true,"affinity_key":"ParentId","affinity_divider":2}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-queue-answers"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"drop-exchange"}
      - PREVIOUS_STEP_COUNT=1
      - NEXT_STEP_COUNT=2
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - ej2-network
  
  drop-input-column-questions:
    container_name: drop-input-column-questions
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop
      - OPERATOR_PARAMS={"columns_to_keep":["Id","CreationDate","Score","Tags"],"perform_affinity":true,"affinity_key":"Id","affinity_divider":2}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-queue-questions"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"drop-exchange"}
      - PREVIOUS_STEP_COUNT=1
      - NEXT_STEP_COUNT=2
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - ej2-network
  
  joiner1:
    container_name: joiner1
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.joiner
      - OPERATOR_PARAMS={"perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"drop-exchange","routing_key":"0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"joiner-output"}
      - PREVIOUS_STEP_COUNT=2
      - NEXT_STEP_COUNT=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - ej2-network
  
  joiner2:
    container_name: joiner2
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.joiner
      - OPERATOR_PARAMS={"perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"drop-exchange","routing_key":"1"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"joiner-output"}
      - PREVIOUS_STEP_COUNT=2
      - NEXT_STEP_COUNT=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - ej2-network

  group_by_holder:
    container_name: group_by_holder
    image: building-block:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=holders.top_n_holder
      - OPERATOR_PARAMS={"top_n":10, "perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"joiner-output"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"group-output"}
      - PREVIOUS_STEP_COUNT=2
      - NEXT_STEP_COUNT=0
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_holder.py"]
    networks:
      - ej2-network


networks:
  ej2-network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.202.0/24