version: "3.8"
services:
  rabbitmq-tp2:
    container_name: "rabbitmq-tp2"
    image: rabbitmq:3.9.7-management-alpine
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - tp2-network
  
  drop-input-column-answers-1:
    container_name: drop-input-column-answers-1
    image: building-block:basic
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop_topics
      - OPERATOR_PARAMS={"params_by_topic":{"answer.ej1":{"columns_to_keep":["Score","Body"],"perform_affinity":true,"affinity_key":"Score","affinity_divider":1},"answer.ej2":{"columns_to_keep":["OwnerUserId","Score"],"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":1},"answer.ej3":{"columns_to_keep":["CreationDate","ParentId","Score"],"perform_affinity":true,"affinity_key":"ParentId","affinity_divider":1}},"perform_affinity":true,"max_affinity":1}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-answers"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: [ "basic_operator.py" ]
    networks:
      - tp2-network

  drop-input-column-questions-1:
    container_name: drop-input-column-questions-1
    image: building-block:basic
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop_topics
      - OPERATOR_PARAMS={"params_by_topic":{"question.ej2":{"columns_to_keep":["OwnerUserId","Score"],"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":1},"question.ej3":{"columns_to_keep":["Id","CreationDate","Tags","Score"],"perform_affinity":true,"affinity_key":"Id","affinity_divider":1}},"perform_affinity":true,"max_affinity":1}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-questions"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: [ "basic_operator.py" ]
    networks:
      - tp2-network
  ej1-filter-1:
    container_name: ej1-filter-1
    image: building-block:basic
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.filter
      - OPERATOR_PARAMS={"keep_columns":["Body"],"column":"Score","to_compare":10,"op":">", "perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source","routing_key":"answer.ej1.0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"ej1-filter-output"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: [ "basic_operator.py" ]
    networks:
      - tp2-network

  ej1-sentiment-analyser-1:
    container_name: ej1-sentiment-analyser-1
    image: building-block:full
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=operators.sentiment_analysis
      - OPERATOR_PARAMS={"column":"Body", "perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"ej1-filter-output"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"ej1-sa-output"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: [ "basic_operator.py" ]
    networks:
      - tp2-network
  
  ej1-avg-holder-1:
    container_name: ej1-avg-holder-1
    image: building-block:basic
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=holders.avg_holder
      - OPERATOR_PARAMS={"column":"result", "perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"ej1-sa-output"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"ej1-final-output"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=0
    depends_on:
      - "rabbitmq-tp2"
    command: [ "basic_holder.py" ]
    networks:
      - tp2-network
  
  ej3-joiner-1:
    container_name: ej3-joiner-1
    image: building-block:basic
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.joiner
      - OPERATOR_PARAMS={"perform_affinity":true,"perform_affinity":true,"affinity_key":"Year","affinity_divider":1}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source","routing_key":"*.ej3.0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"ej3-output-joiner"}
      - CENTINELS_TO_RECEIVE=2
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: [ "basic_operator.py" ]
    networks:
      - tp2-network
  
  ej3-group-by-holder-1:
    container_name: ej3-group-by-holder-1
    image: building-block:basic
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=holders.top_n_years_holder
      - OPERATOR_PARAMS={"top_n":10, "perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"ej3-output-joiner","routing_key":"0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"ej3-final-output"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=0
    depends_on:
      - "rabbitmq-tp2"
    command: [ "basic_holder.py" ]
    networks:
      - tp2-network

  ej2-user-avg-questions-1:
    container_name: ej2-user-avg-questions-1
    image: building-block:basic
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=holders.user_avg_holder
      - OPERATOR_PARAMS={"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":1}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source","routing_key":"question.ej2.0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"ej2-input-filter-questions"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: [ "basic_holder.py" ]
    networks:
      - tp2-network
  
  ej2-general-avg-questions:
    container_name: ej2-general-avg-questions
    image: building-block:basic
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=holders.general_avg
      - OPERATOR_PARAMS={"perform_affinity":true,"affinity_divider":1}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source","routing_key":"question.ej2.*"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"ej2-input-filter-questions"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: [ "basic_holder.py" ]
    networks:
      - tp2-network
  
  ej2-user-avg-answers-1:
    container_name: ej2-user-avg-answers-1
    image: building-block:basic
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=holders.user_avg_holder
      - OPERATOR_PARAMS={"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":1}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source","routing_key":"answer.ej2.0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"ej2-input-filter-answers"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: [ "basic_holder.py" ]
    networks:
      - tp2-network
  
  ej2-general-avg-answers:
    container_name: ej2-general-avg-answers
    image: building-block:basic
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=holders.general_avg
      - OPERATOR_PARAMS={"perform_affinity":true,"affinity_divider":1}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source","routing_key":"answer.ej2.*"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"ej2-input-filter-answers"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: [ "basic_holder.py" ]
    networks:
      - tp2-network
  
  ej2-user-questions-filter-1:
    container_name: ej2-user-questions-filter-1
    image: building-block:basic
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.user_avg_filter
      - OPERATOR_PARAMS={"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":1}
      - INPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"ej2-input-filter-questions","routing_key":"0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"ej2-output-user-filters"}
      - CENTINELS_TO_RECEIVE=2
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: [ "basic_operator.py" ]
    networks:
      - tp2-network
  
  ej2-user-answers-filter-1:
    container_name: ej2-user-answers-filter-1
    image: building-block:basic
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.user_avg_filter
      - OPERATOR_PARAMS={"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":1}
      - INPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"ej2-input-filter-answers","routing_key":"0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"ej2-output-user-filters"}
      - CENTINELS_TO_RECEIVE=2
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: [ "basic_operator.py" ]
    networks:
      - tp2-network
  
  ej2-user-intersector-1:
    container_name: ej2-user-intersector-1
    image: building-block:basic
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.intersector
      - OPERATOR_PARAMS={"perform_affinity":false,"affinity_key":"OwnerUserId","affinity_divider":1}
      - INPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"ej2-output-user-filters","routing_key":"0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"ej2-output-intersectors"}
      - CENTINELS_TO_RECEIVE=2
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: [ "basic_operator.py" ]
    networks:
      - tp2-network
networks:
  tp2-network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.201.0/24
