version: "3.8"
services:
  rabbitmq-tp2:
    container_name: "rabbitmq-tp2"
    image: rabbitmq:3.9.7-management-alpine
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - tp2-network
  
  input_node-answers:
    container_name: input_node-answers
    image: input_node:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - FILE_TO_PROCESS=data/red_answers.csv
      - CHUNK_SIZE=100
      - OUTPUT_QUEUE_NAME=input-answers
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    volumes:
      - "./data:/app/data"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "input_node.py"]
    networks:
      - tp2-network

  input_node-questions:
    container_name: input_node-questions
    image: input_node:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - FILE_TO_PROCESS=data/red_questions.csv
      - CHUNK_SIZE=100
      - OUTPUT_QUEUE_NAME=input-questions
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    volumes:
      - "./data:/app/data"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "input_node.py"]
    networks:
      - tp2-network
  
  drop-input-column-answers:
    container_name: drop-input-column-answers
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop_topics
      - OPERATOR_PARAMS={"params_by_topic":{"answer.ej1":{"columns_to_keep":["Score","Body"],"perform_affinity":true,"affinity_key":"Score","affinity_divider":1},"answer.ej2":{"columns_to_keep":["OwnerUserId","Score"],"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":1},"answer.ej3":{"columns_to_keep":["CreationDate","ParentId","Score"],"perform_affinity":true,"affinity_key":"ParentId","affinity_divider":1}},"perform_affinity":true,"max_affinity":1}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-answers"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - tp2-network

  drop-input-column-questions:
    container_name: drop-input-column-questions
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop_topics
      - OPERATOR_PARAMS={"params_by_topic":{"question.ej2":{"columns_to_keep":["OwnerUserId","Score"],"perform_affinity":true,"affinity_key":"OwnerUserId","affinity_divider":1},"question.ej3":{"columns_to_keep":["Id","CreationDate","Tags","Score"],"perform_affinity":true,"affinity_key":"Id","affinity_divider":1}},"perform_affinity":true,"max_affinity":1}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-questions"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - tp2-network
  
  ej1-filter-1:
    container_name: ej1-filter-1
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.filter
      - OPERATOR_PARAMS={"keep_columns":["Body"],"column":"Score","to_compare":10,"op":">", "perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source","routing_key":"answer.ej1.0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"ej1-filter-output"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - tp2-network
  
  ej1-sentiment-analyser-1:
    container_name: ej1-sentiment-analyser-1
    image: building-block:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=operators.sentiment_analysis
      - OPERATOR_PARAMS={"column":"Body", "perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"ej1-filter-output"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"ej1-sa-output"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - tp2-network

  ej1-avg-holder-1:
    container_name: ej1-avg-holder-1
    image: building-block:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=holders.avg_holder
      - OPERATOR_PARAMS={"column":"result", "perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"ej1-sa-output"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"ej1-final-output"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=0
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_holder.py"]
    networks:
      - tp2-network

networks:
  tp2-network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.201.0/24
