version: "3.8"
services:
  rabbitmq-tp2:
    container_name: "rabbitmq-tp2"
    image: rabbitmq:3.9.7-management-alpine
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - tp2-network
  
  input_node-answers:
    container_name: input_node-answers
    image: input_node:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - FILE_TO_PROCESS=data/red_answers.csv
      - CHUNK_SIZE=100
      - OUTPUT_QUEUE_NAME=input-answers
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    volumes:
      - "./data:/app/data"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "input_node.py"]
    networks:
      - tp2-network

  input_node-questions:
    container_name: input_node-questions
    image: input_node:latest
    environment: 
      - PYTHONUNBUFFERED=1
      - FILE_TO_PROCESS=data/red_answers.csv
      - CHUNK_SIZE=100
      - OUTPUT_QUEUE_NAME=input-questions
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    volumes:
      - "./data:/app/data"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "input_node.py"]
    networks:
      - tp2-network
  
  drop-input-column-answers:
    container_name: drop-input-column-answers
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop_topics
      - OPERATOR_PARAMS={"columns_to_keep_by_topic":{"answer.ej1":["Score","Body"],"answer.ej2":["OwnerUserId","Score"],"answer.ej3":["CreationDate","ParentId","Score"]}}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-answers"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=0
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - tp2-network

  drop-input-column-questions:
    container_name: drop-input-column-questions
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop_topics
      - OPERATOR_PARAMS={"columns_to_keep_by_topic":{"question.ej2":["OwnerUserId","Score"],"question.ej3":["Id","CreationDate","ParentId","Score"]}}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-questions"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=0 
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - tp2-network

networks:
  tp2-network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.201.0/24
