version: "3.8"
services:
  rabbitmq-tp2:
    container_name: "rabbitmq-tp2"
    image: rabbitmq:3.9.7-management-alpine
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - tp2-network

  drop-input-column-answers-1:
    container_name: drop-input-column-answers-1
    image: building-block:basic
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop_topics
      - OPERATOR_PARAMS={"params_by_topic":{"answer.ej3":{"columns_to_keep":["CreationDate","ParentId","Score"],"perform_affinity":true,"affinity_key":"ParentId","affinity_divider":2}},"perform_affinity":true,"max_affinity":2}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-answers"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - tp2-network

  drop-input-column-answers-2:
    container_name: drop-input-column-answers-2
    image: building-block:basic
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop_topics
      - OPERATOR_PARAMS={"params_by_topic":{"answer.ej3":{"columns_to_keep":["CreationDate","ParentId","Score"],"perform_affinity":true,"affinity_key":"ParentId","affinity_divider":2}},"perform_affinity":true,"max_affinity":2}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-answers"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - tp2-network

  drop-input-column-answers-3:
    container_name: drop-input-column-answers-3
    image: building-block:basic
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop_topics
      - OPERATOR_PARAMS={"params_by_topic":{"answer.ej3":{"columns_to_keep":["CreationDate","ParentId","Score"],"perform_affinity":true,"affinity_key":"ParentId","affinity_divider":2}},"perform_affinity":true,"max_affinity":2}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-answers"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - tp2-network

  drop-input-column-questions-1:
    container_name: drop-input-column-questions-1
    image: building-block:basic
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop_topics
      - OPERATOR_PARAMS={"params_by_topic":{"question.ej3":{"columns_to_keep":["Id","CreationDate","Tags","Score"],"perform_affinity":true,"affinity_key":"Id","affinity_divider":2}},"perform_affinity":true,"max_affinity":2}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-questions"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - tp2-network

  drop-input-column-questions-2:
    container_name: drop-input-column-questions-2
    image: building-block:basic
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop_topics
      - OPERATOR_PARAMS={"params_by_topic":{"question.ej3":{"columns_to_keep":["Id","CreationDate","Tags","Score"],"perform_affinity":true,"affinity_key":"Id","affinity_divider":2}},"perform_affinity":true,"max_affinity":2}
      - INPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"input-questions"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - tp2-network
  
  ej3-joiner-1:
    container_name: ej3-joiner-1
    image: building-block:basic
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.joiner
      - OPERATOR_PARAMS={"perform_affinity":true,"perform_affinity":true,"affinity_key":"Year","affinity_divider":3}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source","routing_key":"*.ej3.0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"ej3-output-joiner"}
      - CENTINELS_TO_RECEIVE=5
      - CENTINELS_TO_SEND=3
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - tp2-network

  ej3-joiner-2:
    container_name: ej3-joiner-2
    image: building-block:basic
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.joiner
      - OPERATOR_PARAMS={"perform_affinity":true,"perform_affinity":true,"affinity_key":"Year","affinity_divider":3}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"qa-source","routing_key":"*.ej3.1"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"ej3-output-joiner"}
      - CENTINELS_TO_RECEIVE=5
      - CENTINELS_TO_SEND=3
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - tp2-network
  
  ej3-group-by-holder-1:
    container_name: ej3-group-by-holder-1
    image: building-block:basic
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=holders.top_n_years_holder
      - OPERATOR_PARAMS={"top_n":10, "perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"ej3-output-joiner","routing_key":"0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"ej3-final-output"}
      - CENTINELS_TO_RECEIVE=2
      - CENTINELS_TO_SEND=0
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_holder.py"]
    networks:
      - tp2-network

  ej3-group-by-holder-2:
    container_name: ej3-group-by-holder-2
    image: building-block:basic
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=holders.top_n_years_holder
      - OPERATOR_PARAMS={"top_n":10, "perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"ej3-output-joiner","routing_key":"1"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"ej3-final-output"}
      - CENTINELS_TO_RECEIVE=2
      - CENTINELS_TO_SEND=0
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_holder.py"]
    networks:
      - tp2-network

  ej3-group-by-holder-3:
    container_name: ej3-group-by-holder-3
    image: building-block:basic
    environment: 
      - PYTHONUNBUFFERED=1
      - BLOCK_ID=1
      - OPERATOR_MODULE=holders.top_n_years_holder
      - OPERATOR_PARAMS={"top_n":10, "perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"direct","exchange_name":"ej3-output-joiner","routing_key":"2"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"ej3-final-output"}
      - CENTINELS_TO_RECEIVE=2
      - CENTINELS_TO_SEND=0
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_holder.py"]
    networks:
      - tp2-network
networks:
  tp2-network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.202.0/24