version: "3.8"
services:
  rabbitmq-tp2:
    container_name: "rabbitmq-tp2"
    image: rabbitmq:3.9.7-management-alpine
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - ej3-network
  
  drop-input-column-answers1:
    container_name: drop-input-column-answers1
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop
      - OPERATOR_PARAMS={"columns_to_keep":["Score"],"perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"input-exchange","routing_key":"0"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"output"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - ej3-network
  
  drop-input-column-answers2:
    container_name: drop-input-column-answers2
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop
      - OPERATOR_PARAMS={"columns_to_keep":["Body"],"perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"input-exchange","routing_key":"1"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"output"}
      - CENTINELS_TO_RECEIVE=1
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - ej3-network

  drop-input-column-answers3:
    container_name: drop-input-column-answers3
    image: building-block:latest
    environment: 
      - BLOCK_ID=1
      - PYTHONUNBUFFERED=1
      - OPERATOR_MODULE=operators.column_drop
      - OPERATOR_PARAMS={"columns_to_keep":["Id"],"perform_affinity":false}
      - INPUT_QUEUE_PARAMS={"pattern":"topic","exchange_name":"input-exchange","routing_key":"*"}
      - OUTPUT_QUEUE_PARAMS={"pattern":"work_queue","queue_name":"output"}
      - CENTINELS_TO_RECEIVE=2
      - CENTINELS_TO_SEND=1
    depends_on:
      - "rabbitmq-tp2"
    command: ["./wait-for", "rabbitmq-tp2:5672", "--", "python", "basic_operator.py"]
    networks:
      - ej3-network

networks:
  ej3-network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.203.0/24